### ISSUE TITLE
thread 'main' panicked at 'Unknown error while starting watching directory "wikipedia-index" [...] tantivy-0.9.1/src/directory/mmap_directory.rs:167:17

### ISSUE THREAD

**Issue by josephrocca** [tantivy-search/tantivy-cli#42] opened 2019-07-23 11:52 UTC
Hi there :) I went through the example in the readme and got an error while creating the schema.

It installed successfully with:
```
cargo install tantivy-cli
```

So I made the directory:
```
mkdir wikipedia-index
```

And went through the interactive schema creation:
```
export RUST_BACKTRACE=1; tantivy new -i wikipedia-index

Creating new index 
Let's define it's schema! 



New field name  ? title
Text or unsigned 32-bit integer (T/I) ? t
Should the field be stored (Y/N) ? y
Should the field be indexed (Y/N) ? y
Should the term be tokenized? (Y/N) ? y
Should the term frequencies (per doc) be in the index (Y/N) ? y
Should the term positions (per doc) be in the index (Y/N) ? y
Add another field (Y/N) ? y



New field name  ? body
Text or unsigned 32-bit integer (T/I) ? t
Should the field be stored (Y/N) ? y
Should the field be indexed (Y/N) ? y
Should the term be tokenized? (Y/N) ? y
Should the term frequencies (per doc) be in the index (Y/N) ? y
Should the term positions (per doc) be in the index (Y/N) ? y
Add another field (Y/N) ? y



New field name  ? url
Text or unsigned 32-bit integer (T/I) ? t
Should the field be stored (Y/N) ? y
Should the field be indexed (Y/N) ? n
Add another field (Y/N) ? n

[
  {
    "name": "title",
    "type": "text",
    "options": {
      "indexing": {
        "record": "position",
        "tokenizer": "en_stem"
      },
      "stored": true
    }
  },
  {
    "name": "body",
    "type": "text",
    "options": {
      "indexing": {
        "record": "position",
        "tokenizer": "en_stem"
      },
      "stored": true
    }
  },
  {
    "name": "url",
    "type": "text",
    "options": {
      "indexing": null,
      "stored": true
    }
  }
]

thread 'main' panicked at 'Unknown error while starting watching directory "wikipedia-index"', /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.9.1/src/directory/mmap_directory.rs:167:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:70
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:215
             at src/libstd/panicking.rs:478
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   4: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:340
   5: tantivy::directory::mmap_directory::MmapDirectory::new
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.9.1/src/directory/mmap_directory.rs:167
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libcore/result.rs:520
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.9.1/src/directory/mmap_directory.rs:164
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.9.1/src/directory/mmap_directory.rs:236
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.9.1/src/directory/mmap_directory.rs:263
   6: tantivy::directory::mmap_directory::MmapDirectory::open
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.9.1/src/directory/mmap_directory.rs:294
   7: tantivy::commands::new::run_new_cli
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.9.1/src/core/index.rs:100
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-cli-0.9.0/src/commands/new.rs:16
   8: tantivy::main
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-cli-0.9.0/src/main.rs:139
   9: std::rt::lang_start::{{closure}}
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libstd/rt.rs:64
  10: main
  11: __libc_start_main
  12: _start
```

I'm using Ubuntu 16.04 in case that matters. I'll probably end up using the actual library anyway but it would have been nice to test out the cli program first.

Thanks!

**Comment by fulmicoton** [comment] 2019-07-24 03:57
@josephrocca The issue has been reported in the past too.

Here is a bit of an explanation...
Tantivy makes it possible to index (write) in one process and read that index in different processes.
It also have a way to make it possible to automatically detect committed changes and keep the reader up to date. The way it makes this possible is by "watching" for file system change in the directory of your index.

In the case of the other reporter, the problem was that the OS limit of watched file descriptor was reached.

Is your filesystem standard ? If so, can you retry after a reboot of your system? Without a code editor open for instance? If you can reproduce, can you inspect the failing syscall using strace?

Either way I think I will remove this feature, as it has proved to be a pain.

**Comment by josephrocca** [comment] 2019-07-24 07:14
Thanks! I can't reboot right now, but I'll give it a shot with a clean slate after I reboot :+1:

**Comment by fulmicoton** [comment] 2019-07-25 00:47
Open [tantivy#602](https://github.com/tantivy-search/tantivy/issues/602)

**Comment by fulmicoton** [comment] 2019-07-31 22:17
tantivy 0.11 should have this problem.

**Closed by fulmicoton** 2019-07-31 22:17 UTC
